name: Victus Spiritus
markdown: kramdown
highlighter: pygments
repository: https://github.com/victusfate/victusspiritus
baseurl: /victusspiritus
url: https://victusfate.github.io/victusspiritus
permalink: pretty
theme: jekyll-theme-lanyon

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets
  compress:
    js:
    css:
  cachebust: hard
  gzip: [ text/css, application/javascript ]