name: Victus Spiritus
markdown: redcarpet
pygments: true
highlighter: pygments
repository: https://github.com/victusfate/victusspiritus
relative_permalinks: false
baseurl: /victusspiritus

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets
  compress:
    js:
    css:
  cachebust: hard
  gzip: [ text/css, application/javascript ]